import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { dynamicForm, submitForm } from '@/src/api/forms';

export default function FormSubmission() { const router = useRouter(); const client = useQueryClient(); const { id } = useLocalSearchParams<{ id: string }>(); const formId = Number(id); const form = useQuery({ queryKey: ['dynamic-form', formId], queryFn: () => dynamicForm(formId), enabled: Number.isInteger(formId) && formId > 0 }); const [data, setData] = useState(''); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => submitForm({ form: form.data?.formName ?? 'General form', submissionDate: new Date().toISOString(), data: data.trim() || undefined }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['form-submissions'] }); Alert.alert('Form submitted', 'Your submission was sent for review.', [{ text: 'Done', onPress: () => router.replace('/form-submissions') }]); }, onError: (value) => setError(apiError(value)) }); if (form.isLoading) return <View style={styles.page}><Text>Loading form...</Text></View>; if (form.isError || !form.data) return <View style={styles.page}><Text style={styles.error}>{apiError(form.error)}</Text></View>; return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Back to forms</Text></Pressable><Text style={styles.title}>{form.data.formName}</Text><Text style={styles.subtitle}>{form.data.description ?? 'Enter submission data using the format requested by your organization.'}</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.card}><Text style={styles.label}>Submission data</Text><TextInput value={data} onChangeText={setData} placeholder="Enter form data" multiline style={styles.input} /></View><Pressable accessibilityRole="button" disabled={mutation.isPending} onPress={() => mutation.mutate()} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Submitting...' : 'Submit form'}</Text></Pressable></ScrollView>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, subtitle: { color: '#64748b', marginTop: 5, marginBottom: 18 } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14 } as const, label: { color: '#475569', fontWeight: '700', marginBottom: 7 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, minHeight: 150, padding: 13, textAlignVertical: 'top', color: '#172033' } as const, error: { backgroundColor: '#fff1f2', color: '#9f1239', padding: 13, borderRadius: 10, marginBottom: 14 } as const, submit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 16, alignItems: 'center' } as const, submitText: { color: '#fff', fontWeight: '800' } as const };
