export const EMAIL_BRAND = {
  companyName: process.env.COMPANY_NAME ?? 'Enterprise ERP',
  logoUrl: process.env.COMPANY_LOGO_URL ?? '',
  supportEmail: process.env.COMPANY_SUPPORT_EMAIL ?? 'support@example.com',
  supportWebsite: process.env.COMPANY_SUPPORT_WEBSITE ?? 'https://example.com',
  address: process.env.COMPANY_ADDRESS ?? '1 Example Street',
  primaryColor: process.env.COMPANY_PRIMARY_COLOR ?? '#2563eb',
  secondaryColor: process.env.COMPANY_SECONDARY_COLOR ?? '#0f172a',
  dangerColor: process.env.COMPANY_DANGER_COLOR ?? '#dc2626',
  warningColor: process.env.COMPANY_WARNING_COLOR ?? '#d97706',
  successColor: process.env.COMPANY_SUCCESS_COLOR ?? '#16a34a',
  backgroundColor: process.env.COMPANY_BACKGROUND_COLOR ?? '#f8fafc',
  borderRadius: '8px',
};

export const EMAIL_TEMPLATE_REQUIREMENTS: Record<string, string[]> = {
  welcome: ['firstName', 'organization', 'ctaUrl', 'ctaText'],
  'password-reset': ['firstName', 'resetLink', 'ctaText'],
  'password-changed': ['firstName', 'organization'],
  'employee-invite': ['firstName', 'organization', 'role', 'ctaUrl', 'ctaText'],
  'employee-onboarded': ['firstName', 'organization'],
  'organization-created': ['organization', 'firstName'],
  'organization-invitation': [
    'firstName',
    'organization',
    'role',
    'ctaUrl',
    'ctaText',
  ],
  'email-verification': ['firstName', 'verificationLink', 'ctaText'],
  'login-alert': ['firstName', 'loginLocation', 'browser', 'device', 'ip'],
  'account-locked': ['firstName', 'organization', 'unlockUrl', 'ctaText'],
  'leave-requested': ['firstName', 'leaveType', 'leaveDates', 'organization'],
  'leave-approved': ['firstName', 'leaveType', 'leaveDates', 'approvalStatus'],
  'leave-rejected': ['firstName', 'leaveType', 'leaveDates', 'approvalStatus'],
  'leave-cancelled': ['firstName', 'leaveType', 'leaveDates'],
  'attendance-reminder': ['firstName', 'organization'],
  'attendance-correction-approved': ['firstName', 'organization'],
  'attendance-correction-rejected': ['firstName', 'organization'],
  'payroll-generated': ['firstName', 'organization'],
  'payslip-ready': ['firstName', 'employeeId', 'organization'],
  'invoice-created': [
    'firstName',
    'invoiceNumber',
    'invoiceAmount',
    'organization',
  ],
  'invoice-paid': [
    'firstName',
    'invoiceNumber',
    'invoiceAmount',
    'organization',
  ],
  'invoice-overdue': [
    'firstName',
    'invoiceNumber',
    'invoiceAmount',
    'organization',
  ],
  'payment-received': [
    'firstName',
    'invoiceNumber',
    'invoiceAmount',
    'organization',
  ],
  'payment-failed': [
    'firstName',
    'invoiceNumber',
    'invoiceAmount',
    'organization',
  ],
  'expense-submitted': ['firstName', 'organization'],
  'expense-approved': ['firstName', 'organization'],
  'expense-rejected': ['firstName', 'organization'],
  'task-assigned': [
    'firstName',
    'taskName',
    'projectName',
    'ctaUrl',
    'ctaText',
  ],
  'task-completed': ['firstName', 'taskName', 'projectName'],
  'project-created': [
    'firstName',
    'projectName',
    'organization',
    'ctaUrl',
    'ctaText',
  ],
  'project-deadline-reminder': ['firstName', 'projectName', 'organization'],
  announcement: ['firstName', 'organization'],
  'weekly-summary': ['firstName', 'organization'],
  'monthly-summary': ['firstName', 'organization'],
  'subscription-activated': [
    'firstName',
    'subscriptionPlan',
    'expiryDate',
    'organization',
  ],
  'subscription-renewed': [
    'firstName',
    'subscriptionPlan',
    'expiryDate',
    'organization',
  ],
  'subscription-expiring': [
    'firstName',
    'subscriptionPlan',
    'expiryDate',
    'organization',
  ],
  'subscription-expired': [
    'firstName',
    'subscriptionPlan',
    'expiryDate',
    'organization',
  ],
  'role-assigned': ['firstName', 'role', 'organization'],
  'permission-changed': ['firstName', 'organization', 'role'],
  'new-device-login': ['firstName', 'loginLocation', 'browser', 'device', 'ip'],
  'security-alert': ['firstName', 'organization', 'loginLocation'],
};
