import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { contact, removeContact } from '@/src/api/crm';
import { useAuth } from '@/src/providers/AuthProvider';
import { can } from '@/src/utils/permissions';

export default function ContactDetail() { const router = useRouter(); const { session } = useAuth(); const client = useQueryClient(); const { id } = useLocalSearchParams<{ id: string }>(); const contactId = Number(id); const canRead = can(session, 'contact.read'); const query = useQuery({ queryKey: ['contact', contactId], queryFn: () => contact(contactId), enabled: canRead && Number.isInteger(contactId) && contactId > 0 }); const removeMutation = useMutation({ mutationFn: () => removeContact(contactId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['contacts'] }); router.replace('/contacts'); } }); if (!canRead) return <View style={styles.page}><Text style={styles.error}>You do not have permission to view contacts.</Text></View>; if (query.isLoading) return <View style={styles.page}><Text>Loading contact...</Text></View>; if (query.isError || !query.data) return <View style={styles.page}><Text style={styles.error}>{apiError(query.error)}</Text><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Go back</Text></Pressable></View>; const current = query.data; const confirmDelete = () => Alert.alert('Delete contact?', 'This action cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => removeMutation.mutate() }]); return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Back to contacts</Text></Pressable><Text style={styles.title}>{current.contactName}</Text>{can(session, 'contact.update') ? <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/contact/[id]/edit', params: { id: String(contactId) } } as never)} style={styles.edit}><Text style={styles.editText}>Edit contact</Text></Pressable> : null}{can(session, 'contact.delete') ? <Pressable accessibilityRole="button" disabled={removeMutation.isPending} onPress={confirmDelete} style={styles.delete}><Text style={styles.deleteText}>{removeMutation.isPending ? 'Deleting...' : 'Delete contact'}</Text></Pressable> : null}<View style={styles.card}>{(['email', 'phoneNumber', 'company', 'jobTitle', 'leadSource', 'contactStatus', 'address', 'website', 'linkedin'] as const).map((key) => <Text key={key} style={styles.detail}>{key}: {String(current[key] ?? 'Not set')}</Text>)}</View></ScrollView>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, edit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 14, alignItems: 'center', marginTop: 14 } as const, editText: { color: '#fff', fontWeight: '800' } as const, delete: { backgroundColor: '#be123c', borderRadius: 10, padding: 14, alignItems: 'center', marginTop: 10 } as const, deleteText: { color: '#fff', fontWeight: '800' } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 18, marginTop: 18 } as const, detail: { color: '#475569', marginBottom: 10 } as const, error: { color: '#9f1239', backgroundColor: '#fff1f2', padding: 14, borderRadius: 10, marginVertical: 16 } as const };
