import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { createContact } from '@/src/api/crm';

export default function AddContact() { const router = useRouter(); const client = useQueryClient(); const [form, setForm] = useState({ contactName: '', email: '', phoneNumber: '', company: '', jobTitle: '', leadSource: '', contactStatus: 'ACTIVE', address: '', website: '', linkedin: '' }); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => createContact({ ...form, email: form.email.trim() || undefined, phoneNumber: form.phoneNumber.trim() || undefined, company: form.company.trim() || undefined, jobTitle: form.jobTitle.trim() || undefined, leadSource: form.leadSource.trim() || undefined, address: form.address.trim() || undefined, website: form.website.trim() || undefined, linkedin: form.linkedin.trim() || undefined }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['contacts'] }); Alert.alert('Contact created', 'The contact was added to CRM.', [{ text: 'Done', onPress: () => router.replace('/contacts') }]); }, onError: (value) => setError(apiError(value)) }); const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value })); const submit = () => { setError(''); if (!form.contactName.trim()) return setError('Contact name is required.'); if (form.email && !/^\S+@\S+\.\S+$/.test(form.email)) return setError('Enter a valid email address.'); mutation.mutate(); }; return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Back to contacts</Text></Pressable><Text style={styles.title}>Add contact</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.card}>{(['contactName', 'email', 'phoneNumber', 'company', 'jobTitle', 'leadSource', 'contactStatus', 'address', 'website', 'linkedin'] as const).map((key) => <Field key={key} label={`${key}${key === 'contactName' ? ' *' : ''}`} value={form[key]} onChangeText={(value) => set(key, value)} placeholder={key} multiline={key === 'address'} />)}</View><Pressable accessibilityRole="button" disabled={mutation.isPending} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Saving...' : 'Create contact'}</Text></Pressable></ScrollView>; }
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={{ marginTop: 13 }}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input, props.multiline && { minHeight: 72, textAlignVertical: 'top' }]} /></View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18, marginBottom: 18 } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14 } as const, label: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 6 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, color: '#172033' } as const, error: { color: '#9f1239', backgroundColor: '#fff1f2', padding: 13, borderRadius: 10, marginBottom: 14 } as const, submit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 16, alignItems: 'center' } as const, submitText: { color: '#fff', fontWeight: '800' } as const };
