import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { createTask } from '@/src/api/tasks';
import { Dropdown } from '@/src/components/Dropdown';

export default function AddTask() {
	const router = useRouter(); const client = useQueryClient();
	const [form, setForm] = useState({ taskName: '', description: '', dueDate: '', priority: 'MEDIUM', status: 'PENDING', driveLink: '', notes: '' }); const [error, setError] = useState('');
	const mutation = useMutation({ mutationFn: createTask, onSuccess: () => { void client.invalidateQueries({ queryKey: ['tasks'] }); Alert.alert('Task created', 'The task was added to your workspace.', [{ text: 'Done', onPress: () => router.replace('/(app)/tasks') }]); }, onError: (value) => setError(apiError(value)) });
	const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
	const submit = () => { setError(''); if (!form.taskName.trim()) { setError('Task name is required.'); return; } mutation.mutate({ ...form, taskName: form.taskName.trim(), description: form.description.trim() || null, dueDate: form.dueDate || null, driveLink: form.driveLink.trim() || null, notes: form.notes.trim() || null }); };
	return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to tasks</Text></Pressable><Text style={styles.title}>Add task</Text><Text style={styles.subtitle}>Create a task in your authorized workspace.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<Section title="Task details"><Field label="Task name *" value={form.taskName} onChangeText={(value) => set('taskName', value)} placeholder="Enter task name" /><Field label="Description" value={form.description} onChangeText={(value) => set('description', value)} placeholder="What needs to be done?" multiline /><Field label="Due date" value={form.dueDate} onChangeText={(value) => set('dueDate', value)} placeholder="YYYY-MM-DD" /></Section><Section title="Planning"><Options label="Priority" value={form.priority} values={['LOW', 'MEDIUM', 'HIGH']} onChange={(value) => set('priority', value)} /><Options label="Status" value={form.status} values={['PENDING', 'IN_PROGRESS']} onChange={(value) => set('status', value)} /><Field label="Google Drive link" value={form.driveLink} onChangeText={(value) => set('driveLink', value)} placeholder="https://drive.google.com/..." keyboardType="url" /><Field label="Notes" value={form.notes} onChangeText={(value) => set('notes', value)} placeholder="Additional notes" multiline /></Section><Pressable disabled={mutation.isPending} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Saving...' : 'Create task'}</Text></Pressable></ScrollView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={{ marginTop: 14 }}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input, props.multiline && { minHeight: 90, textAlignVertical: 'top' }]} /></View>; }
function Options({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <Dropdown label={label} value={value} options={values} onChange={onChange} />; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, subtitle: { color: '#64748b', marginTop: 5, marginBottom: 18 } as const, error: { backgroundColor: '#fff1f2', color: '#9f1239', padding: 13, borderRadius: 10, marginBottom: 14 } as const, section: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14 } as const, sectionTitle: { color: '#172033', fontSize: 18, fontWeight: '800' } as const, label: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 6 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, color: '#172033', backgroundColor: '#fff' } as const, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 } as const, option: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, paddingHorizontal: 11, paddingVertical: 10 } as const, optionSelected: { backgroundColor: '#172033', borderColor: '#172033' } as const, submit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 16, alignItems: 'center' } as const, submitText: { color: '#fff', fontWeight: '800' } as const };