import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { deal, markDealWon } from '@/src/api/crm';
import { useAuth } from '@/src/providers/AuthProvider';

export default function DealDetail() { const router = useRouter(); const client = useQueryClient(); const { session } = useAuth(); const { id } = useLocalSearchParams<{ id: string }>(); const dealId = Number(id); const query = useQuery({ queryKey: ['deal', dealId], queryFn: () => deal(dealId), enabled: Number.isInteger(dealId) && dealId > 0 }); const won = useMutation({ mutationFn: () => markDealWon(dealId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['deal', dealId] }); void client.invalidateQueries({ queryKey: ['deals'] }); Alert.alert('Deal won', 'The deal was marked as won.'); }, onError: (error) => Alert.alert('Unable to mark deal won', apiError(error)) }); if (query.isLoading) return <View style={styles.page}><Text>Loading deal...</Text></View>; if (query.isError || !query.data) return <View style={styles.page}><Text style={styles.error}>{apiError(query.error)}</Text><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Go back</Text></Pressable></View>; const current = query.data; const canEdit = ['ADMIN', 'SUPER_ADMIN'].includes(session?.role ?? ''); return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Back to deals</Text></Pressable><Text style={styles.title}>{current.title}</Text>{canEdit ? <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/deal/[id]/edit', params: { id: String(dealId) } } as never)} style={styles.edit}><Text style={styles.editText}>Edit deal</Text></Pressable> : null}{current.stage !== 'WON' ? <Pressable disabled={won.isPending} onPress={() => won.mutate()} style={styles.won}><Text style={styles.wonText}>{won.isPending ? 'Saving...' : 'Mark deal won'}</Text></Pressable> : null}<View style={styles.card}>{(['value', 'stage', 'probability', 'closeDate', 'contact', 'owner', 'pipeline'] as const).map((key) => <Text key={key} style={styles.detail}>{key}: {String(current[key] ?? 'Not set')}</Text>)}{current.lead ? <Text style={styles.detail}>lead: {current.lead.name ?? 'Not set'}{current.lead.company ? ` · ${current.lead.company}` : ''}</Text> : null}{current.linkedContact ? <Text style={styles.detail}>contact: {current.linkedContact.contactName ?? 'Not set'}{current.linkedContact.company ? ` · ${current.linkedContact.company}` : ''}</Text> : null}</View></ScrollView>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, edit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 14, alignItems: 'center', marginTop: 14 } as const, editText: { color: '#fff', fontWeight: '800' } as const, won: { backgroundColor: '#059669', borderRadius: 10, padding: 14, alignItems: 'center', marginTop: 12 } as const, wonText: { color: '#fff', fontWeight: '800' } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 18, marginTop: 18 } as const, detail: { color: '#475569', marginBottom: 10 } as const, error: { color: '#9f1239', backgroundColor: '#fff1f2', padding: 14, borderRadius: 10, marginVertical: 16 } as const };
