import { useState } from 'react';
import { Link, useRouter } from 'expo-router';
import { Controller, useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { KeyboardAvoidingView, Platform, Pressable, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/src/providers/AuthProvider';
import { apiError } from '@/src/api/client';
const schema = z.object({ email: z.string().email('Enter a valid email'), password: z.string().min(1, 'Password is required') });
type Form = z.infer<typeof schema>;
export default function Login() {
  const { login } = useAuth(); const router = useRouter(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const { control, handleSubmit, formState: { errors } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { email: '', password: '' } });
  const submit = async (values: Form) => { setBusy(true); setError(''); try { const next = await login(values.email.trim(), values.password); router.replace(next.isSuperAdmin ? '/(app)/(tabs)/global' : next.isPlatformAdmin && next.organizationId == null ? '/select-organization' : '/(app)/(tabs)/dashboard'); } catch (e) { setError(apiError(e)); } finally { setBusy(false); } };
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1, backgroundColor: '#fff7ed' }}><View style={{ flex: 1, justifyContent: 'center', padding: 24 }}><Text style={{ color: '#c2410c', fontSize: 14, fontWeight: '700', letterSpacing: 1 }}>ENTERPRISE OPERATIONS</Text><Text style={{ color: '#172033', fontSize: 34, fontWeight: '800', marginTop: 10 }}>Work, in your pocket.</Text><Text style={{ color: '#64748b', fontSize: 16, marginTop: 8, marginBottom: 30 }}>Secure access to your organization workspace.</Text>{error ? <Text style={{ color: '#be123c', backgroundColor: '#fff1f2', padding: 12, borderRadius: 10, marginBottom: 14 }}>{error}</Text> : null}<Controller control={control} name="email" render={({ field: { onChange, value } }) => <><TextInput autoCapitalize="none" keyboardType="email-address" placeholder="Work email" value={value} onChangeText={onChange} style={{ backgroundColor: '#fff', borderWidth: 1, borderColor: '#fed7aa', borderRadius: 12, padding: 16, fontSize: 16 }} />{errors.email ? <Text style={{ color: '#be123c', marginTop: 5 }}>{errors.email.message}</Text> : null}</>} /><Controller control={control} name="password" render={({ field: { onChange, value } }) => <><TextInput secureTextEntry placeholder="Password" value={value} onChangeText={onChange} style={{ backgroundColor: '#fff', borderWidth: 1, borderColor: '#fed7aa', borderRadius: 12, padding: 16, fontSize: 16, marginTop: 14 }} />{errors.password ? <Text style={{ color: '#be123c', marginTop: 5 }}>{errors.password.message}</Text> : null}</>} /><Pressable disabled={busy} onPress={handleSubmit(submit)} style={{ backgroundColor: '#ea580c', padding: 17, borderRadius: 12, alignItems: 'center', marginTop: 22, opacity: busy ? 0.6 : 1 }}><Text style={{ color: '#fff', fontSize: 16, fontWeight: '700' }}>{busy ? 'Signing in...' : 'Sign in'}</Text></Pressable><Link href="/(auth)/forgot-password" asChild><Pressable style={{ alignItems: 'center', padding: 18 }}><Text style={{ color: '#c2410c', fontWeight: '600' }}>Forgot password?</Text></Pressable></Link></View></KeyboardAvoidingView>;
}
