import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, Alert, Modal, Pressable, RefreshControl, ScrollView, Text, TextInput, View } from 'react-native';
import { Building2, Check, ChevronRight, CircleAlert, Pencil, Plus, Trash2 } from '@/src/components/icons';
import { createOrganization, deleteOrganization, listOrganizations, setOrganizationStatus, updateOrganization, type Organization } from '@/src/api/organizations';
import { apiError } from '@/src/api/client';
import { useAuth } from '@/src/providers/AuthProvider';
import { useOrganization } from '@/src/providers/OrganizationProvider';
import { useRouter } from 'expo-router';

type Form = { name: string; slug: string; email: string; adminName: string; adminEmail: string; adminPassword: string };
const blank: Form = { name: '', slug: '', email: '', adminName: '', adminEmail: '', adminPassword: '' };

export default function Organizations() {
  const { session } = useAuth(); const { selectOrganization } = useOrganization(); const router = useRouter();
  const query = useQuery({ queryKey: ['super-admin-organizations'], queryFn: listOrganizations, enabled: session?.isSuperAdmin === true });
  const [editing, setEditing] = useState<Organization | null>(null); const [form, setForm] = useState<Form>(blank); const [busy, setBusy] = useState(false);
  if (!session?.isSuperAdmin) return null;
  const close = () => { setEditing(null); setForm(blank); }; const set = (key: keyof Form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.name.trim()) return Alert.alert('Organization name required'); setBusy(true); try { if (editing) await updateOrganization(editing.id, { name: form.name.trim(), slug: form.slug.trim() || undefined, businessEmail: form.email.trim() || undefined }); else await createOrganization({ name: form.name.trim(), slug: form.slug.trim() || undefined, businessEmail: form.email.trim() || undefined, adminName: form.adminName.trim() || undefined, adminEmail: form.adminEmail.trim() || undefined, adminPassword: form.adminPassword || undefined }); close(); await query.refetch(); } catch (error) { Alert.alert('Could not save organization', apiError(error)); } finally { setBusy(false); } };
  const remove = (org: Organization) => Alert.alert('Delete organization?', `Remove ${org.name} and its tenant data?`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await deleteOrganization(org.id); await query.refetch(); } catch (error) { Alert.alert('Could not delete organization', apiError(error)); } } }]);
  const toggle = async (org: Organization) => { try { await setOrganizationStatus(org.id, org.status === 'ACTIVE' ? 'SUSPENDED' : 'ACTIVE'); await query.refetch(); } catch (error) { Alert.alert('Could not update status', apiError(error)); } };
  return <ScrollView refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => void query.refetch()} />} contentContainerStyle={styles.page}><View style={styles.header}><View><Text style={styles.eyebrow}>Global console</Text><Text style={styles.heading}>Organizations</Text></View><Pressable onPress={() => { setEditing(null); setForm({ ...blank, name: ' ' }); }} style={styles.primary}><Plus color="#fff" size={18} /><Text style={styles.primaryText}>Create</Text></Pressable></View><Text style={styles.description}>Manage tenant workspaces and open an organization context.</Text>{query.isLoading ? <ActivityIndicator color="#ea580c" /> : query.isError ? <ErrorPanel message={apiError(query.error)} /> : query.data?.map((org) => <View key={org.id} style={styles.card}><Pressable disabled={org.status !== 'ACTIVE'} onPress={async () => { await selectOrganization(org.id, org.name); router.replace('/(app)/(tabs)/dashboard'); }} style={styles.row}><Building2 color="#ea580c" size={20} /><View style={styles.grow}><Text style={styles.title}>{org.name}</Text><Text style={styles.muted}>{org.code} · {org.status}</Text></View><ChevronRight color="#94a3b8" size={20} /></Pressable><View style={styles.actions}><Action onPress={() => { setEditing(org); setForm({ ...blank, name: org.name, slug: org.slug }); }} icon={<Pencil color="#2563eb" size={16} />} label="Edit" /><Action onPress={() => void toggle(org)} icon={<Check color="#047857" size={16} />} label={org.status === 'ACTIVE' ? 'Suspend' : 'Activate'} /><Action onPress={() => remove(org)} icon={<Trash2 color="#be123c" size={16} />} label="Delete" danger /></View></View>)}<Modal visible={form.name !== ''} transparent animationType="slide" onRequestClose={close}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>{editing ? 'Edit organization' : 'Create organization'}</Text><Field label="Name" value={form.name.trim()} onChangeText={(value) => set('name', value)} /><Field label="Slug" value={form.slug} onChangeText={(value) => set('slug', value)} /><Field label="Business email" value={form.email} onChangeText={(value) => set('email', value)} keyboardType="email-address" />{!editing && <><Field label="Admin name" value={form.adminName} onChangeText={(value) => set('adminName', value)} /><Field label="Admin email" value={form.adminEmail} onChangeText={(value) => set('adminEmail', value)} keyboardType="email-address" /><Field label="Admin password" value={form.adminPassword} onChangeText={(value) => set('adminPassword', value)} secureTextEntry /></>}<View style={styles.modalActions}><Pressable onPress={close} style={styles.cancel}><Text>Cancel</Text></Pressable><Pressable disabled={busy} onPress={() => void save()} style={styles.primary}><Text style={styles.primaryText}>{busy ? 'Saving...' : editing ? 'Update' : 'Create'}</Text></Pressable></View></View></View></Modal></ScrollView>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'email-address'; secureTextEntry?: boolean }) { return <View style={{ marginTop: 12 }}><Text style={styles.label}>{label}</Text><TextInput {...props} placeholder={label} style={styles.input} autoCapitalize="none" /></View>; }
function Action({ onPress, icon, label, danger }: { onPress: () => void; icon: React.ReactNode; label: string; danger?: boolean }) { return <Pressable onPress={onPress} style={styles.action}>{icon}<Text style={{ color: danger ? '#be123c' : '#475569', fontSize: 12, fontWeight: '700' }}>{label}</Text></Pressable>; }
+function ErrorPanel({ message }: { message: string }) { return <View style={styles.error}><CircleAlert color="#be123c" size={20} /><Text style={{ color: '#9f1239', flex: 1 }}>{message}</Text></View>; }
function ErrorPanel({ message }: { message: string }) { return <View style={styles.error}><CircleAlert color="#be123c" size={20} /><Text style={{ color: '#9f1239', flex: 1 }}>{message}</Text></View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 }, header: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'flex-end' as const }, eyebrow: { color: '#64748b', fontSize: 14 }, heading: { color: '#172033', fontSize: 29, fontWeight: '800' as const, marginTop: 3 }, description: { color: '#64748b', marginTop: 6, marginBottom: 20 }, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 10 }, row: { flexDirection: 'row' as const, alignItems: 'center' as const }, grow: { flex: 1, marginLeft: 13 }, title: { color: '#172033', fontWeight: '800' as const, fontSize: 16 }, muted: { color: '#64748b', marginTop: 5 }, actions: { borderTopWidth: 1, borderTopColor: '#f1f5f9', marginTop: 14, paddingTop: 12, flexDirection: 'row' as const, gap: 18 }, action: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5 }, primary: { backgroundColor: '#ea580c', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 10, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 }, primaryText: { color: '#fff', fontWeight: '800' as const }, overlay: { flex: 1, justifyContent: 'flex-end' as const, backgroundColor: 'rgba(15,23,42,0.45)' }, modal: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22 }, modalTitle: { color: '#172033', fontSize: 22, fontWeight: '800' as const }, label: { color: '#475569', fontSize: 12, fontWeight: '700' as const }, input: { backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, padding: 12, marginTop: 5 }, modalActions: { flexDirection: 'row' as const, justifyContent: 'flex-end' as const, gap: 10, marginTop: 20 }, cancel: { padding: 12 }, error: { backgroundColor: '#fff1f2', padding: 15, borderRadius: 12, flexDirection: 'row' as const, gap: 10 } };
