import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, Alert, Modal, Pressable, RefreshControl, ScrollView, Text, TextInput, View } from 'react-native';
import { CircleAlert, Pencil, Plus, Trash2, UsersRound } from '@/src/components/icons';
import { createUser, deleteUser, listUsers, setUserStatus, updateUser, type PlatformUser } from '@/src/api/users';
import { apiError } from '@/src/api/client';
import { useAuth } from '@/src/providers/AuthProvider';

type Form = { name: string; email: string; password: string; role: string };
const blank: Form = { name: '', email: '', password: '', role: 'ADMIN' };

export default function Users() {
  const { session } = useAuth(); const query = useQuery({ queryKey: ['super-admin-users'], queryFn: listUsers, enabled: session?.isSuperAdmin === true });
  const [editing, setEditing] = useState<PlatformUser | null>(null); const [form, setForm] = useState<Form>(blank); const [busy, setBusy] = useState(false);
  if (!session?.isSuperAdmin) return null;
  const active = query.data?.filter((user) => user.isActive).length ?? 0; const close = () => { setEditing(null); setForm(blank); }; const set = (key: keyof Form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.name.trim() || !form.email.trim() || (!editing && !form.password)) return Alert.alert('Name, email, and password are required'); setBusy(true); try { if (editing) await updateUser(editing.id, { name: form.name.trim(), email: form.email.trim(), role: form.role, ...(form.password ? { password: form.password } : {}) }); else await createUser({ name: form.name.trim(), email: form.email.trim(), password: form.password, role: form.role }); close(); await query.refetch(); } catch (error) { Alert.alert('Could not save user', apiError(error)); } finally { setBusy(false); } };
  const remove = (user: PlatformUser) => Alert.alert('Delete user?', `Remove ${user.name} from the platform?`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await deleteUser(user.id); await query.refetch(); } catch (error) { Alert.alert('Could not delete user', apiError(error)); } } }]); const toggle = async (user: PlatformUser) => { try { await setUserStatus(user.id, !user.isActive); await query.refetch(); } catch (error) { Alert.alert('Could not update user', apiError(error)); } };
  return <ScrollView refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => void query.refetch()} />} contentContainerStyle={styles.page}><View style={styles.header}><View><Text style={styles.eyebrow}>Global console</Text><Text style={styles.heading}>Users</Text></View><Pressable onPress={() => { setEditing(null); setForm({ ...blank, name: ' ' }); }} style={styles.primary}><Plus color="#fff" size={18} /><Text style={styles.primaryText}>Create</Text></Pressable></View><View style={styles.summary}><UsersRound color="#2563eb" size={24} /><View style={{ marginLeft: 13 }}><Text style={styles.muted}>Active accounts</Text><Text style={styles.count}>{query.data ? `${active} / ${query.data.length}` : '...'}</Text></View></View>{query.isLoading ? <ActivityIndicator color="#ea580c" /> : query.isError ? <ErrorPanel message={apiError(query.error)} /> : query.data?.map((user) => <View key={user.id} style={styles.card}><Text style={styles.title}>{user.name}</Text><Text style={styles.muted}>{user.email}</Text><Text style={{ color: user.isActive ? '#047857' : '#be123c', marginTop: 8, fontSize: 12, fontWeight: '700' }}>{user.role} · {user.isActive ? 'ACTIVE' : 'INACTIVE'}</Text><View style={styles.actions}><Action onPress={() => { setEditing(user); setForm({ name: user.name, email: user.email, password: '', role: user.role }); }} icon={<Pencil color="#2563eb" size={16} />} label="Edit" /><Action onPress={() => void toggle(user)} icon={<UsersRound color="#047857" size={16} />} label={user.isActive ? 'Deactivate' : 'Activate'} /><Action onPress={() => remove(user)} icon={<Trash2 color="#be123c" size={16} />} label="Delete" danger /></View></View>)}<Modal visible={form.name !== ''} transparent animationType="slide" onRequestClose={close}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>{editing ? 'Edit user' : 'Create user'}</Text><Field label="Full name" value={form.name.trim()} onChangeText={(value) => set('name', value)} /><Field label="Email" value={form.email} onChangeText={(value) => set('email', value)} keyboardType="email-address" /><Field label={editing ? 'New password (optional)' : 'Password'} value={form.password} onChangeText={(value) => set('password', value)} secureTextEntry /><Field label="Role" value={form.role} onChangeText={(value) => set('role', value.toUpperCase())} /><View style={styles.modalActions}><Pressable onPress={close} style={styles.cancel}><Text>Cancel</Text></Pressable><Pressable disabled={busy} onPress={() => void save()} style={styles.primary}><Text style={styles.primaryText}>{busy ? 'Saving...' : editing ? 'Update' : 'Create'}</Text></Pressable></View></View></View></Modal></ScrollView>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'email-address'; secureTextEntry?: boolean }) { return <View style={{ marginTop: 12 }}><Text style={styles.label}>{label}</Text><TextInput {...props} placeholder={label} style={styles.input} autoCapitalize="none" /></View>; }
function Action({ onPress, icon, label, danger }: { onPress: () => void; icon: React.ReactNode; label: string; danger?: boolean }) { return <Pressable onPress={onPress} style={styles.action}>{icon}<Text style={{ color: danger ? '#be123c' : '#475569', fontSize: 12, fontWeight: '700' }}>{label}</Text></Pressable>; }
function ErrorPanel({ message }: { message: string }) { return <View style={styles.error}><CircleAlert color="#be123c" size={20} /><Text style={{ color: '#9f1239', flex: 1 }}>{message}</Text></View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 }, header: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'flex-end' as const }, eyebrow: { color: '#64748b', fontSize: 14 }, heading: { color: '#172033', fontSize: 29, fontWeight: '800' as const, marginTop: 3 }, summary: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginTop: 20, marginBottom: 18, flexDirection: 'row' as const, alignItems: 'center' as const }, count: { color: '#172033', fontWeight: '800' as const, fontSize: 24 }, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 10 }, title: { color: '#172033', fontWeight: '800' as const, fontSize: 16 }, muted: { color: '#64748b', marginTop: 4 }, actions: { borderTopWidth: 1, borderTopColor: '#f1f5f9', marginTop: 14, paddingTop: 12, flexDirection: 'row' as const, gap: 18 }, action: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5 }, primary: { backgroundColor: '#ea580c', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 10, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 }, primaryText: { color: '#fff', fontWeight: '800' as const }, overlay: { flex: 1, justifyContent: 'flex-end' as const, backgroundColor: 'rgba(15,23,42,0.45)' }, modal: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22 }, modalTitle: { color: '#172033', fontSize: 22, fontWeight: '800' as const }, label: { color: '#475569', fontSize: 12, fontWeight: '700' as const }, input: { backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, padding: 12, marginTop: 5 }, modalActions: { flexDirection: 'row' as const, justifyContent: 'flex-end' as const, gap: 10, marginTop: 20 }, cancel: { padding: 12 }, error: { backgroundColor: '#fff1f2', padding: 15, borderRadius: 12, flexDirection: 'row' as const, gap: 10 } };
