import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { createProject } from '@/src/api/modules';
import { useAuth } from '@/src/providers/AuthProvider';
import { Dropdown } from '@/src/components/Dropdown';

export default function AddProject() {
	const router = useRouter(); const client = useQueryClient(); const { session } = useAuth();
	const allowed = ['ADMIN', 'SUPER_ADMIN', 'MANAGER'].includes(session?.role ?? '');
	const [form, setForm] = useState({ projectName: '', startDate: '', endDate: '', description: '', client: '', category: '', projectType: '', specificTask: '', priority: 'MEDIUM', status: 'NOT_STARTED', budget: '', remarks: '', driveLink: '', finalDeliverablesLink: '' }); const [error, setError] = useState('');
	const mutation = useMutation({ mutationFn: createProject, onSuccess: () => { void client.invalidateQueries({ queryKey: ['projects'] }); Alert.alert('Project created', 'The project was added to your workspace.', [{ text: 'Done', onPress: () => router.replace('/(app)/projects') }]); }, onError: (value) => setError(apiError(value)) });
	const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
	const submit = () => { setError(''); if (!form.projectName.trim()) { setError('Project name is required.'); return; } mutation.mutate({ ...form, projectName: form.projectName.trim(), startDate: form.startDate || undefined, endDate: form.endDate || undefined, description: form.description.trim() || undefined, client: form.client.trim() || undefined, clientName: form.client.trim() || undefined, category: form.category.trim() || undefined, projectType: form.projectType || undefined, specificTask: form.specificTask.trim() || undefined, budget: form.budget ? Number(form.budget) : undefined, remarks: form.remarks.trim() || undefined, driveLink: form.driveLink.trim() || undefined, finalDeliverablesLink: form.finalDeliverablesLink.trim() || undefined }); };
	if (!allowed) return <View style={styles.page}><Text style={styles.title}>Add project</Text><Text style={styles.error}>You do not have permission to create projects.</Text></View>;
	return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to projects</Text></Pressable><Text style={styles.title}>Add project</Text><Text style={styles.subtitle}>Create a project in your authorized workspace.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<Section title="Project details"><Field label="Project name *" value={form.projectName} onChangeText={(value) => set('projectName', value)} placeholder="Enter project name" /><Field label="Client" value={form.client} onChangeText={(value) => set('client', value)} placeholder="Client name" /><Field label="Category" value={form.category} onChangeText={(value) => set('category', value)} placeholder="Project category" /><Field label="Description" value={form.description} onChangeText={(value) => set('description', value)} placeholder="Project description" multiline /></Section><Section title="Schedule and planning"><Field label="Start date" value={form.startDate} onChangeText={(value) => set('startDate', value)} placeholder="YYYY-MM-DD" /><Field label="End date" value={form.endDate} onChangeText={(value) => set('endDate', value)} placeholder="YYYY-MM-DD" /><Options label="Project type" value={form.projectType} values={['EVENT_MANAGEMENT', 'PRODUCTION_EM', 'DIGITAL_MARKETING', 'PRODUCTION_DM', 'PRODUCTION_OTHER', 'TECH_PROJECTS']} onChange={(value) => set('projectType', value)} /><Options label="Priority" value={form.priority} values={['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']} onChange={(value) => set('priority', value)} /><Options label="Status" value={form.status} values={['NOT_STARTED', 'IN_PROGRESS', 'IN_APPROVAL', 'BLOCKED_CANCELLED', 'POSTPONED', 'COMPLETED']} onChange={(value) => set('status', value)} /><Field label="Budget" value={form.budget} onChangeText={(value) => set('budget', value)} placeholder="0" keyboardType="decimal-pad" /><Field label="Specific task" value={form.specificTask} onChangeText={(value) => set('specificTask', value)} placeholder="Primary project task" /><Field label="Remarks" value={form.remarks} onChangeText={(value) => set('remarks', value)} placeholder="Project remarks" multiline /></Section><Section title="Links"><Field label="Google Drive link" value={form.driveLink} onChangeText={(value) => set('driveLink', value)} placeholder="https://drive.google.com/..." keyboardType="url" /><Field label="Final deliverables link" value={form.finalDeliverablesLink} onChangeText={(value) => set('finalDeliverablesLink', value)} placeholder="https://..." keyboardType="url" /></Section><Pressable disabled={mutation.isPending} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Saving...' : 'Create project'}</Text></Pressable></ScrollView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={{ marginTop: 14 }}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input, props.multiline && { minHeight: 90, textAlignVertical: 'top' }]} /></View>; }
function Options({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <Dropdown label={label} value={value} options={values} onChange={onChange} />; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, subtitle: { color: '#64748b', marginTop: 5, marginBottom: 18 } as const, error: { backgroundColor: '#fff1f2', color: '#9f1239', padding: 13, borderRadius: 10, marginTop: 14 } as const, section: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14 } as const, sectionTitle: { color: '#172033', fontSize: 18, fontWeight: '800' } as const, label: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 6 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, color: '#172033', backgroundColor: '#fff' } as const, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 } as const, option: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, paddingHorizontal: 10, paddingVertical: 9 } as const, optionSelected: { backgroundColor: '#172033', borderColor: '#172033' } as const, submit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 16, alignItems: 'center' } as const, submitText: { color: '#fff', fontWeight: '800' } as const };