import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { createInvoice } from '@/src/api/invoices';

export default function AddInvoice() { const router = useRouter(); const client = useQueryClient(); const [form, setForm] = useState({ invoiceNo: '', customer: '', clientEmail: '', totalAmount: '', dueDate: '', notes: '' }); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => createInvoice({ invoiceNo: form.invoiceNo.trim(), customer: form.customer.trim() || undefined, clientEmail: form.clientEmail.trim() || undefined, totalAmount: Number(form.totalAmount), dueDate: form.dueDate || undefined, notes: form.notes.trim() || undefined }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['invoices'] }); Alert.alert('Invoice created', 'The invoice was saved.', [{ text: 'Done', onPress: () => router.replace('/invoices') }]); }, onError: (value) => setError(apiError(value)) }); const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value })); const submit = () => { setError(''); if (!form.invoiceNo.trim()) return setError('Invoice number is required.'); if (!Number.isFinite(Number(form.totalAmount)) || Number(form.totalAmount) < 0) return setError('Enter a valid total amount.'); if (form.dueDate && !/^\d{4}-\d{2}-\d{2}$/.test(form.dueDate)) return setError('Use a due date in YYYY-MM-DD format.'); mutation.mutate(); }; return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to invoices</Text></Pressable><Text style={styles.title}>Add invoice</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.card}><Field label="Invoice number *" value={form.invoiceNo} onChangeText={(value) => set('invoiceNo', value)} /><Field label="Customer" value={form.customer} onChangeText={(value) => set('customer', value)} /><Field label="Client email" value={form.clientEmail} onChangeText={(value) => set('clientEmail', value)} keyboardType="email-address" autoCapitalize="none" /><Field label="Total amount *" value={form.totalAmount} onChangeText={(value) => set('totalAmount', value)} keyboardType="decimal-pad" /><Field label="Due date" value={form.dueDate} onChangeText={(value) => set('dueDate', value)} placeholder="YYYY-MM-DD" /><Field label="Notes" value={form.notes} onChangeText={(value) => set('notes', value)} multiline /></View><Pressable disabled={mutation.isPending} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Saving...' : 'Create invoice'}</Text></Pressable></ScrollView>; }
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={{ marginTop: 14 }}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} /></View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18, marginBottom: 18 } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14 } as const, label: { color: '#475569', fontWeight: '700', marginBottom: 6 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, color: '#172033' } as const, submit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 16, alignItems: 'center' } as const, submitText: { color: '#fff', fontWeight: '800' } as const, error: { color: '#9f1239', backgroundColor: '#fff1f2', padding: 13, borderRadius: 10, marginBottom: 14 } as const };
