import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { createTimesheet } from '@/src/api/modules';

export default function AddTimesheet() {
	const router = useRouter(); const client = useQueryClient();
	const [form, setForm] = useState({ task: '', date: '', hours: '', status: 'PENDING', project: '', notes: '' }); const [error, setError] = useState('');
	const mutation = useMutation({ mutationFn: createTimesheet, onSuccess: () => { void client.invalidateQueries({ queryKey: ['timesheets'] }); Alert.alert('Timesheet submitted', 'Your work log was added.', [{ text: 'Done', onPress: () => router.replace('/(app)/timesheets') }]); }, onError: (value) => setError(apiError(value)) });
	const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
	const submit = () => { setError(''); const hours = Number(form.hours); if (!form.task.trim()) { setError('Task is required.'); return; } if (!/^\d{4}-\d{2}-\d{2}$/.test(form.date)) { setError('Use a date in YYYY-MM-DD format.'); return; } if (!Number.isFinite(hours) || hours <= 0) { setError('Hours must be greater than zero.'); return; } mutation.mutate({ task: form.task.trim(), date: form.date, hours, status: form.status, project: form.project.trim() || undefined, notes: form.notes.trim() || undefined }); };
	return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to timesheets</Text></Pressable><Text style={styles.title}>Add timesheet</Text><Text style={styles.subtitle}>Record work for manager review and reporting.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.section}><Text style={styles.sectionTitle}>Work log</Text><Field label="Task *" value={form.task} onChangeText={(value) => set('task', value)} placeholder="What work did you complete?" /><Field label="Date *" value={form.date} onChangeText={(value) => set('date', value)} placeholder="YYYY-MM-DD" /><Field label="Hours *" value={form.hours} onChangeText={(value) => set('hours', value)} placeholder="0.00" keyboardType="decimal-pad" /><Field label="Project" value={form.project} onChangeText={(value) => set('project', value)} placeholder="Project name" /><Field label="Notes" value={form.notes} onChangeText={(value) => set('notes', value)} placeholder="Add context for approval" multiline /></View><View style={styles.section}><Text style={styles.sectionTitle}>Approval status</Text><View style={styles.options}>{['PENDING', 'SUBMITTED'].map((status) => <Pressable key={status} onPress={() => set('status', status)} style={[styles.option, form.status === status && styles.optionSelected]}><Text style={{ color: form.status === status ? '#fff' : '#334155', fontWeight: '700' }}>{status}</Text></Pressable>)}</View></View><Pressable disabled={mutation.isPending} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Saving...' : 'Submit timesheet'}</Text></Pressable></ScrollView>;
}
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={{ marginTop: 14 }}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input, props.multiline && { minHeight: 90, textAlignVertical: 'top' }]} /></View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, subtitle: { color: '#64748b', marginTop: 5, marginBottom: 18 } as const, error: { backgroundColor: '#fff1f2', color: '#9f1239', padding: 13, borderRadius: 10, marginBottom: 14 } as const, section: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14 } as const, sectionTitle: { color: '#172033', fontSize: 18, fontWeight: '800' } as const, label: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 6 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, color: '#172033', backgroundColor: '#fff' } as const, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 } as const, option: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, paddingHorizontal: 11, paddingVertical: 10 } as const, optionSelected: { backgroundColor: '#172033', borderColor: '#172033' } as const, submit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 16, alignItems: 'center' } as const, submitText: { color: '#fff', fontWeight: '800' } as const };