import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useLocalSearchParams, useRouter } from 'expo-router';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { leaveRequest, removeLeaveRequest } from '@/src/api/leave';

export default function LeaveDetail() {
  const router = useRouter(); const client = useQueryClient(); const { id } = useLocalSearchParams<{ id: string }>(); const requestId = Number(id);
  const query = useQuery({ queryKey: ['leave', requestId], queryFn: () => leaveRequest(requestId), enabled: Number.isInteger(requestId) && requestId > 0 });
  const removal = useMutation({ mutationFn: () => removeLeaveRequest(requestId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['leave'] }); router.replace('/leave'); }, onError: (error) => Alert.alert('Unable to cancel leave', apiError(error)) });
  if (query.isLoading) return <View style={styles.page}><Text>Loading leave request...</Text></View>;
  if (query.isError || !query.data) return <View style={styles.page}><Text style={styles.error}>{apiError(query.error)}</Text></View>;
  const current = query.data; const active = current.status !== 'APPROVED' && current.status !== 'REJECTED' && current.status !== 'CANCELLED';
  return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to leave</Text></Pressable><Text style={styles.title}>{current.leaveType ?? 'Leave request'}</Text><Text style={styles.status}>{current.status ?? 'PENDING'}</Text><View style={styles.card}><Detail label="Dates" value={`${current.startDate ?? 'Not set'} to ${current.endDate ?? 'Not set'}`} /><Detail label="Reason" value={current.reason || 'No reason provided'} /><Detail label="Employee" value={current.employee?.name || 'My request'} /></View>{active ? <><Link href={{ pathname: '/leave/[id]/edit', params: { id: String(requestId) } }} asChild><Pressable style={styles.action}><Text style={styles.actionText}>Edit request</Text></Pressable></Link><Pressable disabled={removal.isPending} onPress={() => Alert.alert('Cancel this request?', 'The request will be removed from the leave workflow.', [{ text: 'Keep', style: 'cancel' }, { text: 'Cancel request', style: 'destructive', onPress: () => removal.mutate() }])} style={styles.cancel}><Text style={styles.cancelText}>{removal.isPending ? 'Cancelling...' : 'Cancel request'}</Text></Pressable></> : null}</ScrollView>;
}
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, status: { color: '#c2410c', fontWeight: '800', marginTop: 8 } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginTop: 18 } as const, detail: { borderBottomWidth: 1, borderBottomColor: '#e2e8f0', paddingVertical: 12 } as const, label: { color: '#64748b', fontSize: 12, fontWeight: '700' } as const, value: { color: '#172033', marginTop: 4, fontSize: 16 } as const, action: { backgroundColor: '#2563eb', borderRadius: 10, padding: 15, alignItems: 'center', marginTop: 16 } as const, actionText: { color: '#fff', fontWeight: '800' } as const, cancel: { padding: 15, alignItems: 'center', marginTop: 8 } as const, cancelText: { color: '#be123c', fontWeight: '800' } as const, error: { color: '#9f1239', backgroundColor: '#fff1f2', padding: 14, borderRadius: 10 } as const };
