export type InvoicePdfContext = {
  invoiceNo: string;
  customer: string;
  issueDate: string;
  dueDate: string;
  totalAmount: string;
  companyName: string;
  notes?: string | null;
  paymentInstructions?: string | null;
  terms?: string | null;
};

function escapePdfText(value: string) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

export function buildInvoicePdfBuffer(context: InvoicePdfContext) {
  const lines = [
    `${context.companyName}`,
    `Invoice ${context.invoiceNo}`,
    `Customer: ${context.customer}`,
    `Issue Date: ${context.issueDate}`,
    `Due Date: ${context.dueDate}`,
    `Total Amount: ${context.totalAmount}`,
    '',
    'Payment Instructions',
    context.paymentInstructions?.trim() ||
      'Please remit payment within the agreed terms.',
    '',
    'Terms & Conditions',
    context.terms?.trim() || 'Payment is due upon receipt of the invoice.',
    '',
    'Notes',
    context.notes?.trim() || 'Invoice generated through the ERP workflow.',
  ];

  const contentLines = [
    '0 0 0 rg',
    'BT',
    '/F1 18 Tf',
    '50 780 Td',
    `(Invoice ${escapePdfText(context.invoiceNo)}) Tj`,
    'ET',
    'BT',
    '/F1 12 Tf',
    '50 748 Td',
    `(Prepared for ${escapePdfText(context.customer)}) Tj`,
    'ET',
  ];

  let y = 720;
  for (const line of lines.slice(2)) {
    contentLines.push('BT');
    contentLines.push('/F1 10 Tf');
    contentLines.push(`50 ${y} Td`);
    contentLines.push(`(${escapePdfText(line)}) Tj`);
    contentLines.push('ET');
    y -= 14;
  }

  contentLines.push('0.8 0.85 0.9 rg');
  contentLines.push('50 100 495 1 re f');
  contentLines.push('0 0 0 rg');
  contentLines.push('BT');
  contentLines.push('/F1 10 Tf');
  contentLines.push('50 82 Td');
  contentLines.push(
    '(This document was generated by the enterprise ERP invoice workflow.) Tj',
  );
  contentLines.push('ET');

  const content = contentLines.join('\n');
  const pdf = [
    '%PDF-1.4',
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${Buffer.byteLength(content, 'utf8')} >> stream\n${content}\nendstream endobj`,
  ];

  const objects = pdf.join('\n');
  const offsets: number[] = [];
  let pdfBody = '';
  let offset = 0;
  for (const entry of pdf) {
    offsets.push(offset);
    pdfBody += `${entry}\n`;
    offset = Buffer.byteLength(pdfBody, 'utf8');
  }

  const xrefOffset = Buffer.byteLength(pdfBody, 'utf8');
  const xref = ['xref', `0 ${pdf.length + 1}`, '0000000000 65535 f '];
  for (const offset of offsets) {
    xref.push(`${String(offset).padStart(10, '0')} 00000 n `);
  }
  const footer = [
    'trailer',
    `<< /Size ${pdf.length + 1} /Root 1 0 R >>`,
    'startxref',
    `${xrefOffset}`,
    '%%EOF',
  ];

  return Buffer.from([objects, xref.join('\n'), footer.join('\n')].join('\n'));
}
