import { api, unwrap } from './client';

export type ManagedFile = { id: number; originalName: string; mimeType: string; size: number; category?: string | null; createdAt: string; downloadUrl?: string; previewUrl?: string | null; signedDownloadUrl?: string };
export type FileListResponse = { items: ManagedFile[]; total: number; page: number; limit: number };
export async function files(): Promise<ManagedFile[]> { const payload = unwrap<unknown>((await api.get('/files', { params: { page: 1, limit: 50 } })).data); if (Array.isArray(payload)) return payload as ManagedFile[]; if (payload && typeof payload === 'object' && 'items' in payload && Array.isArray((payload as FileListResponse).items)) return (payload as FileListResponse).items; return []; }
export async function filesByEntity(entityType: string, entityId: number): Promise<ManagedFile[]> { const payload = unwrap<unknown>((await api.get(`/files/entity/${entityType}/${entityId}`)).data); if (Array.isArray(payload)) return payload as ManagedFile[]; if (payload && typeof payload === 'object' && 'items' in payload && Array.isArray((payload as FileListResponse).items)) return (payload as FileListResponse).items; return []; }
export async function uploadFile(file: { uri: string; name: string; type: string }, organizationId: number) { const body = new FormData(); body.append('file', file as unknown as Blob); body.append('module', 'ORGANIZATION'); body.append('entityType', 'Organization'); body.append('entityId', String(organizationId)); return unwrap<ManagedFile>((await api.post('/files/upload', body, { headers: { 'Content-Type': 'multipart/form-data' } })).data); }
export async function uploadProfilePhoto(file: { uri: string; name: string; type: string }, userId: number) { const body = new FormData(); body.append('file', file as unknown as Blob); body.append('module', 'users'); body.append('entityType', 'User'); body.append('entityId', String(userId)); body.append('category', 'Profile Photo'); body.append('isPublic', 'true'); return unwrap<ManagedFile>((await api.post('/files/upload', body, { headers: { 'Content-Type': 'multipart/form-data' } })).data); }
export async function uploadExpenseReceipt(file: { uri: string; name: string; type: string }, expenseId: number) { const body = new FormData(); body.append('file', file as unknown as Blob); body.append('module', 'expenses'); body.append('entityType', 'Expense'); body.append('entityId', String(expenseId)); body.append('category', 'Receipt'); body.append('isPublic', 'false'); return unwrap<ManagedFile>((await api.post('/files/upload', body, { headers: { 'Content-Type': 'multipart/form-data' } })).data); }
export async function file(id: number) { return unwrap<ManagedFile>((await api.get(`/files/${id}`)).data); }
export async function previewFile(id: number) { return unwrap<unknown>((await api.get(`/files/preview/${id}`)).data); }
export async function downloadFile(id: number) { return unwrap<unknown>((await api.get(`/files/download/${id}`)).data); }
export async function updateFile(id: number, payload: Partial<{ originalName: string; category: string; tags: string; isPublic: string; metadata: string }>) { return unwrap<ManagedFile>((await api.patch(`/files/${id}`, payload)).data); }
export async function removeFile(id: number) { return unwrap<unknown>((await api.delete(`/files/${id}`)).data); }
