import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { convertQuoteToInvoice, quote } from '@/src/api/quotes';
import { useAuth } from '@/src/providers/AuthProvider';

export default function QuoteDetail() { const router = useRouter(); const client = useQueryClient(); const { session } = useAuth(); const { id } = useLocalSearchParams<{ id: string }>(); const quoteId = Number(id); const query = useQuery({ queryKey: ['quote', quoteId], queryFn: () => quote(quoteId), enabled: Number.isInteger(quoteId) && quoteId > 0 }); const canConvert = ['ADMIN', 'SUPER_ADMIN'].includes(session?.role ?? ''); const mutation = useMutation({ mutationFn: () => convertQuoteToInvoice(quoteId), onSuccess: (result) => { void client.invalidateQueries({ queryKey: ['quote', quoteId] }); Alert.alert('Quote converted', `Invoice ${result.invoiceNo} was created.`, [{ text: 'View invoice', onPress: () => router.push({ pathname: '/invoice/[id]', params: { id: String(result.id) } } as never) }]); }, onError: (value) => Alert.alert('Unable to convert quote', apiError(value)) }); if (query.isLoading) return <View style={styles.page}><Text>Loading quote...</Text></View>; if (query.isError || !query.data) return <View style={styles.page}><Text style={styles.error}>{apiError(query.error)}</Text><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Go back</Text></Pressable></View>; const current = query.data; return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Back to quotes</Text></Pressable><Text style={styles.title}>Quote #{current.id}</Text><View style={styles.card}><Text style={styles.detail}>Deal: {current.deal?.title ?? current.dealId}</Text><Text style={styles.detail}>Contact: {current.contact?.contactName ?? current.contactId}</Text><Text style={styles.detail}>Total: {current.total}</Text><Text style={styles.detail}>Status: {current.status}</Text><Text style={styles.detail}>Valid until: {current.validTill}</Text>{current.notes ? <Text style={styles.detail}>Notes: {current.notes}</Text> : null}</View><Text style={styles.heading}>Line items</Text>{current.items.map((item, index) => <View key={item.id ?? index} style={styles.item}><Text style={styles.detail}>{item.name}</Text><Text style={styles.muted}>{item.quantity} × {item.price}</Text></View>)}{canConvert && current.status !== 'CONVERTED' ? <Pressable accessibilityRole="button" disabled={mutation.isPending} onPress={() => mutation.mutate()} style={styles.action}><Text style={styles.actionText}>{mutation.isPending ? 'Converting...' : 'Convert to invoice'}</Text></Pressable> : null}</ScrollView>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 18, marginTop: 18 } as const, item: { backgroundColor: '#fff', borderRadius: 12, padding: 15, marginBottom: 9 } as const, detail: { color: '#475569', marginBottom: 9 } as const, muted: { color: '#64748b' } as const, heading: { color: '#172033', fontSize: 20, fontWeight: '800', marginTop: 24, marginBottom: 10 } as const, error: { color: '#9f1239', backgroundColor: '#fff1f2', padding: 14, borderRadius: 10, marginVertical: 16 } as const, action: { backgroundColor: '#ea580c', borderRadius: 10, padding: 15, alignItems: 'center', marginTop: 18 } as const, actionText: { color: '#fff', fontWeight: '800' } as const };
