import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { timesheet, updateTimesheet } from '@/src/api/modules';

export default function EditTimesheet() {
  const router = useRouter();
  const client = useQueryClient();
  const { id } = useLocalSearchParams<{ id: string }>();
  const timesheetId = Number(id);
  const query = useQuery({ queryKey: ['timesheet', timesheetId], queryFn: () => timesheet(timesheetId), enabled: Number.isInteger(timesheetId) && timesheetId > 0 });
  const [form, setForm] = useState({ task: '', date: '', hours: '', project: '', notes: '', status: 'PENDING' });
  const [error, setError] = useState('');
  useEffect(() => { if (query.data) setForm({ task: query.data.task, date: query.data.date.slice(0, 10), hours: String(query.data.hours), project: query.data.project ?? '', notes: query.data.notes ?? '', status: query.data.status }); }, [query.data]);
  const mutation = useMutation({ mutationFn: () => updateTimesheet(timesheetId, { task: form.task.trim(), date: form.date, hours: Number(form.hours), project: form.project.trim() || undefined, notes: form.notes.trim() || undefined, status: form.status }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['timesheet', timesheetId] }); void client.invalidateQueries({ queryKey: ['timesheets'] }); Alert.alert('Timesheet updated', 'Your work log was saved.', [{ text: 'Done', onPress: () => router.back() }]); }, onError: (value) => setError(apiError(value)) });
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = () => { setError(''); const hours = Number(form.hours); if (!form.task.trim()) return setError('Task is required.'); if (!/^\d{4}-\d{2}-\d{2}$/.test(form.date)) return setError('Use a date in YYYY-MM-DD format.'); if (!Number.isFinite(hours) || hours <= 0) return setError('Hours must be greater than zero.'); mutation.mutate(); };
  if (query.isLoading) return <View style={styles.page}><Text>Loading timesheet...</Text></View>;
  if (query.isError || !query.data) return <View style={styles.page}><Text style={styles.error}>{apiError(query.error)}</Text></View>;
  if (query.data.status === 'APPROVED') return <View style={styles.page}><Text style={styles.error}>Approved timesheets cannot be edited.</Text></View>;
  return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={() => router.back()}><Text style={styles.back}>Back to timesheet</Text></Pressable><Text style={styles.title}>Edit timesheet</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.card}><Field label="Task *" value={form.task} onChangeText={(value) => set('task', value)} placeholder="What work did you complete?" /><Field label="Date *" value={form.date} onChangeText={(value) => set('date', value)} placeholder="YYYY-MM-DD" /><Field label="Hours *" value={form.hours} onChangeText={(value) => set('hours', value)} placeholder="0.00" keyboardType="decimal-pad" /><Field label="Project" value={form.project} onChangeText={(value) => set('project', value)} placeholder="Project name" /><Field label="Notes" value={form.notes} onChangeText={(value) => set('notes', value)} placeholder="Add context for approval" multiline /><Text style={styles.label}>Status</Text><View style={styles.options}>{['PENDING', 'SUBMITTED'].map((status) => <Pressable key={status} accessibilityRole="button" onPress={() => set('status', status)} style={[styles.option, form.status === status && styles.selected]}><Text style={{ color: form.status === status ? '#fff' : '#334155', fontWeight: '700' }}>{status}</Text></Pressable>)}</View></View><Pressable accessibilityRole="button" disabled={mutation.isPending} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Saving...' : 'Save changes'}</Text></Pressable></ScrollView>;
}
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={{ marginTop: 14 }}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input, props.multiline && { minHeight: 80, textAlignVertical: 'top' }]} /></View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18, marginBottom: 18 } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14 } as const, label: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 6 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, color: '#172033', backgroundColor: '#fff' } as const, options: { flexDirection: 'row', gap: 8, marginTop: 8 } as const, option: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, paddingHorizontal: 11, paddingVertical: 10 } as const, selected: { backgroundColor: '#172033', borderColor: '#172033' } as const, error: { backgroundColor: '#fff1f2', color: '#9f1239', padding: 13, borderRadius: 10, marginBottom: 14 } as const, submit: { backgroundColor: '#ea580c', borderRadius: 10, padding: 16, alignItems: 'center' } as const, submitText: { color: '#fff', fontWeight: '800' } as const };
