const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const reportPath = path.join(root, 'PRODUCTION_READINESS_REPORT.md');
const auditTime = new Date().toISOString();

function run(command, args, options = {}) {
  try {
    const output = execFileSync(command, args, {
      cwd: root,
      encoding: 'utf8',
      stdio: options.capture === false ? 'inherit' : ['ignore', 'pipe', 'pipe'],
      timeout: options.timeout ?? 15 * 60 * 1000,
    });
    return { passed: true, output: output.trim() };
  } catch (error) {
    return {
      passed: false,
      output: [error.stdout, error.stderr, error.message]
        .filter(Boolean)
        .join('\n')
        .trim(),
    };
  }
}

function git(args) {
  return run('git', args, { timeout: 30 * 1000 });
}

function npm(args, timeout = 30 * 60 * 1000) {
  if (process.platform !== 'win32') return run('npm', args, { timeout });
  return run(process.env.ComSpec || 'cmd.exe', ['/d', '/s', '/c', `npm.cmd ${args.join(' ')}`], { timeout });
}

function migrationCount() {
  const migrationsPath = path.join(root, 'api', 'prisma', 'migrations');
  return fs.readdirSync(migrationsPath, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name !== '.').length;
}

function trackedSecretScan() {
  const result = git(['grep', '-nE', '(JWT_(ACCESS|REFRESH)_SECRET|DATABASE_URL|SMTP_PASS|AWS_S3_SECRET_ACCESS_KEY)=.{8,}', '--', '*.env', '*.env.local', '*.env.production', '*.env.test']);
  return !result.passed;
}

const artifactPaths = [
  'api/uploads',
  'app/temp-export',
  'app/temp-export-verify',
  'app/web-build',
  'api/dist',
  'api/coverage',
  'app/dist',
  'web/.next',
];

function trackedArtifacts() {
  const result = git(['ls-files', '--', ...artifactPaths]);
  return result.output;
}

function existingLocalArtifacts() {
  return artifactPaths.filter((artifactPath) => fs.existsSync(path.join(root, artifactPath)));
}

const checks = [];
function addCheck(name, result) {
  checks.push({ name, status: result.passed ? 'PASS' : 'BLOCKED', detail: result.output });
}

const head = git(['rev-parse', 'HEAD']);
const branch = git(['branch', '--show-current']);
const workingTree = git(['status', '--porcelain']);

addCheck('Repository typecheck', npm(['run', 'typecheck']));
addCheck('Repository tests', npm(['test']));
addCheck('Repository lint', npm(['run', 'lint']));
addCheck('Prisma schema validation', npm(['--prefix', 'api', 'run', 'prisma:validate']));
addCheck('Prisma migration status', npm(['--prefix', 'api', 'run', 'prisma:migrate:status']));

const secretScanPassed = trackedSecretScan();
checks.push({
  name: 'Tracked secret scan',
  status: secretScanPassed ? 'PASS' : 'BLOCKED',
  detail: secretScanPassed ? 'No matching secret assignments found in tracked files.' : 'Potential secret assignment found by git grep.',
});

const trackedArtifactList = trackedArtifacts();
checks.push({
  name: 'Tracked generated/runtime artifacts',
  status: trackedArtifactList ? 'BLOCKED' : 'PASS',
  detail: trackedArtifactList || 'No generated build output or runtime upload paths are tracked.',
});

const localArtifactList = existingLocalArtifacts();
checks.push({
  name: 'Local generated/runtime artifacts',
  status: localArtifactList.length > 0 ? 'WARN' : 'PASS',
  detail: localArtifactList.length > 0
    ? `Ignored local paths present: ${localArtifactList.join(', ')}`
    : 'No local generated/runtime artifact directories are present.',
});

const localEnvironment = process.env.RELEASE_AUDIT_LIVE === '1' ? 'REQUESTED' : 'NOT VERIFIED';
checks.push({
  name: 'Production environment and live smoke checks',
  status: localEnvironment === 'REQUESTED' ? 'WARN' : 'NOT VERIFIED',
  detail: 'Vercel variables, live database state, deployment health, and authenticated smoke tests require an explicit deployment environment.',
});

const blocked = checks.some((check) => check.status === 'BLOCKED');
const unverified = checks.some((check) => check.status === 'NOT VERIFIED');
const status = blocked ? 'BLOCKED' : unverified ? 'CONDITIONAL' : 'READY FOR PRODUCTION';
const report = [
  '# Production Readiness Report',
  '',
  `**Status:** ${status}`,
  `**Audited:** ${auditTime}`,
  `**Commit:** ${head.output || 'unknown'}`,
  `**Branch:** ${branch.output || 'detached'}`,
  `**Migration directories:** ${migrationCount()}`,
  `**Working tree:** ${workingTree.output ? 'has local changes' : 'clean'}`,
  '',
  'This report is generated by `npm run release:audit`. It records repository checks only; production environment and live deployment checks are explicitly marked when unavailable.',
  '',
  '## Checks',
  '',
  '| Check | Status |',
  '| --- | --- |',
  ...checks.map((check) => `| ${check.name} | ${check.status} |`),
  '',
  '## Details',
  '',
  ...checks.flatMap((check) => [
    `### ${check.name}`,
    '',
    '```text',
    check.detail || 'No additional output.',
    '```',
    '',
  ]),
  '## Release Gate',
  '',
  blocked
    ? 'Release is blocked. Resolve all blocked checks and rerun the audit.'
    : unverified
      ? 'Release is conditional. Verify production environment, deployment health, database state, and authenticated smoke tests before release.'
      : 'All configured release checks passed.',
  '',
].join('\n');

fs.writeFileSync(reportPath, report, 'utf8');
console.log(`Wrote ${path.relative(root, reportPath)} with status ${status}.`);
if (blocked) process.exitCode = 1;