import { useQuery } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import * as FileSystem from 'expo-file-system/legacy';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { monthlyAttendanceReport } from '@/src/api/attendance';
import { useAuth } from '@/src/providers/AuthProvider';

export default function AttendanceReport() {
	const router = useRouter(); const { session } = useAuth(); const allowed = ['HR', 'ADMIN', 'SUPER_ADMIN'].includes(session?.role ?? '');
	const now = new Date(); const [month, setMonth] = useState(String(now.getMonth() + 1)); const [year, setYear] = useState(String(now.getFullYear()));
	const monthNumber = Number(month); const yearNumber = Number(year); const query = useQuery({ queryKey: ['attendance', 'monthly-report', monthNumber, yearNumber], queryFn: () => monthlyAttendanceReport({ month: monthNumber, year: yearNumber }), enabled: allowed && monthNumber >= 1 && monthNumber <= 12 && yearNumber >= 2000 });
	if (!allowed) return <View style={styles.page}><Text style={styles.title}>Monthly attendance report</Text><Text style={styles.error}>You do not have permission to view attendance reports.</Text></View>;
	const payload = query.data && typeof query.data === 'object' ? query.data as { month?: string; year?: number; rows?: Record<string, unknown>[]; total?: number } : {}; const rows = payload.rows ?? [];
	const exportCsv = async () => { const header = ['Employee', 'Department', 'Present', 'Absent', 'Late', 'Leave', 'Attendance %']; const lines = rows.map((row) => [row.employeeName, row.department, row.presentCount, row.absentCount, row.lateCount, row.leaveCount, row.attendancePercent].map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')); const uri = `${FileSystem.documentDirectory}attendance-${monthNumber}-${yearNumber}.csv`; await FileSystem.writeAsStringAsync(uri, [header.join(','), ...lines].join('\n')); Alert.alert('Report exported', `Saved to ${uri}`); };
	return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to attendance</Text></Pressable><Text style={styles.title}>Monthly attendance report</Text><Text style={styles.subtitle}>Review attendance totals across your authorized organization scope.</Text><View style={styles.filters}><Text style={styles.label}>Month</Text><TextInput value={month} onChangeText={setMonth} keyboardType="number-pad" placeholder="1-12" style={styles.input} /><Text style={styles.label}>Year</Text><TextInput value={year} onChangeText={setYear} keyboardType="number-pad" placeholder="2026" style={styles.input} /><Pressable disabled={rows.length === 0} onPress={exportCsv} style={styles.export}><Text style={styles.exportText}>Export CSV</Text></Pressable></View>{query.isLoading ? <Text style={styles.muted}>Loading report...</Text> : null}{query.isError ? <Text style={styles.error}>{apiError(query.error)}</Text> : null}{!query.isLoading && !query.isError && rows.length === 0 ? <Text style={styles.muted}>No attendance data for this period.</Text> : null}{rows.map((row, index) => <View key={String(row.employeeId ?? index)} style={styles.card}><Text style={styles.cardTitle}>{String(row.employeeName ?? 'Employee')}</Text><Text style={styles.muted}>{String(row.department ?? 'Unassigned department')} · {String(row.role ?? 'Employee')}</Text><View style={styles.grid}>{[['Present', row.presentCount], ['Absent', row.absentCount], ['Late', row.lateCount], ['Leave', row.leaveCount], ['Working days', row.workingDays], ['Attendance', `${row.attendancePercent ?? 0}%`]].map(([label, value]) => <View key={String(label)} style={styles.metric}><Text style={styles.metricLabel}>{String(label)}</Text><Text style={styles.metricValue}>{String(value ?? 0)}</Text></View>)}</View><Text style={styles.muted}>Worked: {String(row.totalWorkedHours ?? 0)}h · Overtime: {String(row.overtimeHours ?? 0)}h · Shortfall: {String(row.shortfallHours ?? 0)}h</Text></View>)}</ScrollView>;
}
const styles: Record<string, any> = { export: { backgroundColor: '#172033', borderRadius: 10, padding: 13, alignItems: 'center', marginTop: 14 }, exportText: { color: '#fff', fontWeight: '800' }, page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, subtitle: { color: '#64748b', marginTop: 5, marginBottom: 18 } as const, filters: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 18 } as const, label: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 6, marginTop: 8 } as const, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 12, color: '#172033' } as const, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 10 } as const, cardTitle: { color: '#172033', fontSize: 17, fontWeight: '800', marginBottom: 5 } as const, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 14 } as const, metric: { minWidth: '29%', flex: 1, backgroundColor: '#f8fafc', borderRadius: 10, padding: 10 } as const, metricLabel: { color: '#64748b', fontSize: 11 } as const, metricValue: { color: '#172033', fontWeight: '800', fontSize: 16, marginTop: 3 } as const, muted: { color: '#64748b', marginTop: 5 } as const, error: { backgroundColor: '#fff1f2', color: '#9f1239', padding: 13, borderRadius: 10, marginTop: 14 } as const };