import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { apiError } from '@/src/api/client';
import { assignShift, shifts } from '@/src/api/attendance';
import { employees } from '@/src/api/employees';
import { useAuth } from '@/src/providers/AuthProvider';

export default function AssignShift() {
	const router = useRouter(); const client = useQueryClient(); const { session } = useAuth(); const allowed = ['HR', 'ADMIN', 'SUPER_ADMIN'].includes(session?.role ?? '');
	const employeeQuery = useQuery({ queryKey: ['employees', 'shift-assignment'], queryFn: employees, enabled: allowed }); const shiftQuery = useQuery({ queryKey: ['attendance', 'shifts'], queryFn: shifts, enabled: allowed });
	const [employeeId, setEmployeeId] = useState<number>(); const [shiftId, setShiftId] = useState<number>(); const [error, setError] = useState('');
	const mutation = useMutation({ mutationFn: () => assignShift({ employeeId: employeeId!, shiftId: shiftId! }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['employees'] }); void client.invalidateQueries({ queryKey: ['attendance'] }); Alert.alert('Shift assigned', 'The employee attendance profile was updated.', [{ text: 'Done', onPress: () => router.replace('/attendance') }]); }, onError: (value) => setError(apiError(value)) });
	const submit = () => { setError(''); if (!employeeId || !shiftId) { setError('Select an employee and a shift.'); return; } mutation.mutate(); };
	if (!allowed) return <View style={styles.page}><Text style={styles.title}>Assign shift</Text><Text style={styles.error}>You do not have permission to assign shifts.</Text></View>;
	return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to attendance</Text></Pressable><Text style={styles.title}>Assign shift</Text><Text style={styles.subtitle}>Assign an active shift within your authorized scope.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<PickerSection title="Employee" loading={employeeQuery.isLoading} empty={!employeeQuery.data?.length} options={employeeQuery.data ?? []} selected={employeeId} getId={(item) => item.id} getLabel={(item) => `${item.name}${item.department ? ` · ${item.department}` : ''}`} onSelect={setEmployeeId} /><PickerSection title="Shift" loading={shiftQuery.isLoading} empty={!shiftQuery.data?.length} options={shiftQuery.data ?? []} selected={shiftId} getId={(item) => item.id} getLabel={(item) => `${item.name} · ${item.type}`} onSelect={setShiftId} /><Pressable disabled={mutation.isPending} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{mutation.isPending ? 'Saving...' : 'Assign shift'}</Text></Pressable></ScrollView>;
}
function PickerSection<T extends { id: number }>({ title, loading, empty, options, selected, getId, getLabel, onSelect }: { title: string; loading: boolean; empty: boolean; options: T[]; selected?: number; getId: (item: T) => number; getLabel: (item: T) => string; onSelect: (id: number) => void }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{loading ? <Text style={styles.muted}>Loading options...</Text> : empty ? <Text style={styles.muted}>No options available.</Text> : <View style={styles.options}>{options.map((item) => <Pressable key={getId(item)} onPress={() => onSelect(getId(item))} style={[styles.option, selected === getId(item) && styles.selected]}><Text style={{ color: selected === getId(item) ? '#fff' : '#334155', fontWeight: '700' }}>{getLabel(item)}</Text></Pressable>)}</View>}</View>; }
const styles = { page: { padding: 20, backgroundColor: '#f8fafc', flexGrow: 1 } as const, back: { color: '#2563eb', fontWeight: '700' } as const, title: { color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 18 } as const, subtitle: { color: '#64748b', marginTop: 5, marginBottom: 18 } as const, section: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginTop: 18 } as const, sectionTitle: { color: '#172033', fontSize: 18, fontWeight: '800', marginBottom: 10 } as const, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 } as const, option: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, padding: 11 } as const, selected: { backgroundColor: '#172033', borderColor: '#172033' } as const, muted: { color: '#64748b' } as const, error: { color: '#9f1239', backgroundColor: '#fff1f2', padding: 13, borderRadius: 10, marginTop: 14 } as const, submit: { backgroundColor: '#0369a1', borderRadius: 10, padding: 16, alignItems: 'center', marginTop: 20 } as const, submitText: { color: '#fff', fontWeight: '800' } as const };