import * as ImagePicker from 'expo-image-picker';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { accountProfile, employeeProfile, updateAccountProfile, updateEmployeeProfile } from '@/src/api/auth';
import { apiError } from '@/src/api/client';
import { filesByEntity, uploadProfilePhoto } from '@/src/api/files';
import { AppButton } from '@/src/components/AppButton';
import { StatePanel } from '@/src/components/StatePanel';
import { useAuth } from '@/src/providers/AuthProvider';
import { tokens } from '@/src/theme/tokens';

function formatDate(value?: string | null) { if (!value) return 'Not available'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Not available' : date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }); }
function formatDateTime(value?: string | null) { if (!value) return 'Not available'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Not available' : date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }); }
function initials(name?: string | null) { return name?.trim().charAt(0).toUpperCase() || 'U'; }

export default function Profile() {
  const router = useRouter();
  const client = useQueryClient();
  const { session, logout } = useAuth();
  const account = useQuery({ queryKey: ['profile', 'account'], queryFn: accountProfile });
  const employee = useQuery({ queryKey: ['profile', 'employee'], queryFn: employeeProfile });
  const [form, setForm] = useState({ fullName: '', email: '', phone: '', designation: '', department: '', role: '', location: '' });
  const [avatarUrl, setAvatarUrl] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  const userId = employee.data?.user?.id ?? employee.data?.id ?? session?.user.id;
  const avatarQuery = useQuery({ queryKey: ['profile', 'avatar', userId], queryFn: () => filesByEntity('User', userId as number), enabled: userId != null });
  const save = useMutation({ mutationFn: async () => { await updateAccountProfile({ name: form.fullName.trim(), phone: form.phone.trim() || undefined, address: form.location.trim() || undefined, designation: form.designation.trim() || undefined }); if (employee.data) await updateEmployeeProfile({ phoneNumber: form.phone.trim() || undefined, address: form.location.trim() || undefined }); }, onSuccess: () => { void client.invalidateQueries({ queryKey: ['profile'] }); setError(''); setMessage('Profile details saved successfully.'); }, onError: (value) => { setMessage(''); setError(apiError(value)); } });
  const avatar = useMutation({ mutationFn: (file: { uri: string; name: string; type: string }) => uploadProfilePhoto(file, userId as number), onSuccess: (file) => { setAvatarUrl(file.previewUrl ?? file.downloadUrl ?? null); void client.invalidateQueries({ queryKey: ['profile', 'avatar', userId] }); setMessage('Profile photo updated.'); }, onError: (value) => setError(apiError(value)) });

  useEffect(() => { const accountData = account.data; const employeeData = employee.data; if (accountData || employeeData) setForm((current) => ({ ...current, fullName: accountData?.name ?? employeeData?.name ?? session?.user.name ?? current.fullName, email: accountData?.email ?? employeeData?.email ?? session?.user.email ?? current.email, phone: accountData?.phone ?? employeeData?.phoneNumber ?? employeeData?.phone ?? current.phone, designation: accountData?.designation ?? employeeData?.designation ?? employeeData?.position ?? current.designation, department: employeeData?.department ?? current.department, role: employeeData?.user?.role ?? session?.role ?? current.role, location: accountData?.address ?? employeeData?.address ?? current.location })); }, [account.data, employee.data, session]);
  useEffect(() => { const preferred = avatarQuery.data?.find((file) => file.category === 'Profile Photo') ?? avatarQuery.data?.[0]; if (preferred) setAvatarUrl(preferred.previewUrl ?? preferred.downloadUrl ?? null); }, [avatarQuery.data]);

  const joinedAt = employee.data?.user?.createdAt ?? employee.data?.hireDate;
  const active = employee.data?.user?.isActive ?? true;
  const initialsValue = useMemo(() => initials(form.fullName || session?.user.name), [form.fullName, session?.user.name]);
  const pickAvatar = async () => { if (!userId) return; const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError('Gallery permission is required to choose a profile photo.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.9 }); if (result.canceled || !result.assets[0]) return; const selected = result.assets[0]; if (!['image/jpeg', 'image/png'].includes(selected.mimeType ?? 'image/jpeg')) { setError('Please choose a JPG, JPEG, or PNG image.'); return; } if ((selected.fileSize ?? 0) > 5 * 1024 * 1024) { setError('Profile photo must be 5 MB or smaller.'); return; } avatar.mutate({ uri: selected.uri, name: selected.fileName ?? 'profile-photo.jpg', type: selected.mimeType ?? 'image/jpeg' }); };
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));

  if (account.isLoading && employee.isLoading) return <View style={styles.page}><StatePanel kind="loading" message="Loading your profile..." /></View>;
  return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back</Text></Pressable><Text style={styles.title}>My Profile</Text><Text style={styles.subtitle}>Manage your personal information and account details.</Text>{message ? <View style={styles.success}><Text style={styles.successText}>{message}</Text></View> : null}{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text></View> : null}<View style={styles.hero}>{avatarUrl ? <Image source={{ uri: avatarUrl }} style={styles.avatar} /> : <View style={styles.avatarFallback}><Text style={styles.avatarText}>{initialsValue}</Text></View>}<View style={styles.heroInfo}><Text style={styles.heroName}>{form.fullName || 'User'}</Text><Text style={styles.heroMuted}>{form.designation || form.role || 'Employee'}</Text><Text style={styles.heroMuted}>{form.department || 'Not assigned'}</Text><View style={styles.roleBadge}><Text style={styles.roleText}>{form.role || 'EMPLOYEE'}</Text></View></View><AppButton label="Change photo" loading={avatar.isPending} onPress={() => void pickAvatar()} variant="secondary" style={styles.photoButton} /></View><View style={styles.section}><Text style={styles.sectionTitle}>Personal Information</Text><Text style={styles.sectionHint}>Update the details visible on your profile.</Text><Field label="Full name" value={form.fullName} onChangeText={(value) => set('fullName', value)} /><Field label="Email" value={form.email} editable={false} /><Field label="Phone" value={form.phone} onChangeText={(value) => set('phone', value)} keyboardType="phone-pad" /><Field label="Department" value={form.department || 'Not assigned'} editable={false} /><Field label="Designation" value={form.designation} onChangeText={(value) => set('designation', value)} /><Field label="Role" value={form.role} editable={false} /><Field label="Location" value={form.location} onChangeText={(value) => set('location', value)} /></View><AppButton label="Save changes" loading={save.isPending} onPress={() => { setError(''); setMessage(''); save.mutate(); }} /><View style={styles.section}><Text style={styles.sectionTitle}>Account</Text><View style={styles.accountGrid}><Info label="Account status" value={active ? 'Active' : 'Inactive'} tone={active ? 'success' : 'danger'} /><Info label="Date joined" value={formatDate(joinedAt)} /><Info label="Last login" value="Not available" /></View></View><AppButton label="Sign out securely" variant="danger" onPress={() => void logout()} /></ScrollView>;
}

function Field({ label, value, onChangeText, editable = true, keyboardType = 'default' }: { label: string; value: string; onChangeText?: (value: string) => void; editable?: boolean; keyboardType?: 'default' | 'phone-pad' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} editable={editable} keyboardType={keyboardType} style={[styles.input, !editable && styles.readonly]} /></View>; }
function Info({ label, value, tone }: { label: string; value: string; tone?: 'success' | 'danger' }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={[styles.infoValue, tone === 'success' && styles.successValue, tone === 'danger' && styles.dangerValue]}>{value}</Text></View>; }

const styles = { page: { padding: tokens.spacing.page, backgroundColor: tokens.colors.page, flexGrow: 1, gap: tokens.spacing.section } as const, back: { color: tokens.colors.info, fontWeight: '700' } as const, title: { ...tokens.type.title, color: tokens.colors.ink } as const, subtitle: { color: tokens.colors.muted, marginTop: -8 } as const, hero: { backgroundColor: tokens.colors.ink, borderRadius: 18, padding: tokens.spacing.card, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.control, flexWrap: 'wrap' } as const, avatar: { width: 78, height: 78, borderRadius: 39 } as const, avatarFallback: { width: 78, height: 78, borderRadius: 39, backgroundColor: tokens.colors.primary, alignItems: 'center', justifyContent: 'center' } as const, avatarText: { color: '#fff', fontSize: 30, fontWeight: '800' } as const, heroInfo: { flex: 1, minWidth: 140 } as const, heroName: { color: '#fff', fontSize: 20, fontWeight: '800' } as const, heroMuted: { color: '#cbd5e1', marginTop: 3 } as const, roleBadge: { alignSelf: 'flex-start', backgroundColor: '#334155', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, marginTop: 8 } as const, roleText: { color: '#fdba74', fontSize: 11, fontWeight: '800' } as const, photoButton: { minWidth: 120 } as const, section: { backgroundColor: tokens.colors.surface, borderRadius: tokens.radius.card, padding: tokens.spacing.card } as const, sectionTitle: { ...tokens.type.section, color: tokens.colors.ink } as const, sectionHint: { color: tokens.colors.muted, marginTop: 4, marginBottom: 8 } as const, field: { marginTop: 12 } as const, label: { color: tokens.colors.text, ...tokens.type.label, marginBottom: 6 } as const, input: { borderWidth: 1, borderColor: tokens.colors.border, borderRadius: tokens.radius.control, padding: 12, color: tokens.colors.ink, minHeight: 46 } as const, readonly: { backgroundColor: '#f1f5f9', color: tokens.colors.muted } as const, accountGrid: { gap: 10 } as const, info: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: tokens.radius.control, backgroundColor: '#f8fafc', padding: 13 } as const, infoValue: { color: tokens.colors.ink, fontWeight: '800', marginTop: 5 } as const, successValue: { color: tokens.colors.success } as const, dangerValue: { color: tokens.colors.danger } as const, success: { backgroundColor: tokens.colors.successSoft, borderRadius: tokens.radius.control, padding: 13 } as const, successText: { color: '#047857', fontWeight: '700' } as const, error: { backgroundColor: tokens.colors.dangerSoft, borderRadius: tokens.radius.control, padding: 13 } as const, errorText: { color: tokens.colors.danger, fontWeight: '700' } as const };
