-- Add missing soft-delete columns to align the live database with the Prisma schema.

CREATE TABLE IF NOT EXISTS "ProjectLink" (
	"id" SERIAL NOT NULL,
	"projectId" INTEGER NOT NULL,
	"title" TEXT NOT NULL,
	"url" TEXT NOT NULL,
	"createdById" INTEGER NOT NULL,
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"deletedAt" TIMESTAMP(3),

	CONSTRAINT "ProjectLink_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Payslip" (
	"id" SERIAL NOT NULL,
	"payrollEntryId" INTEGER NOT NULL,
	"employeeId" INTEGER NOT NULL,
	"month" INTEGER NOT NULL,
	"year" INTEGER NOT NULL,
	"basicSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"hra" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"allowances" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"bonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"overtime" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"reimbursements" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"grossEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"pfDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"esiDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"professionalTax" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"tdsDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"lossOfPay" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"otherDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"totalDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"netPay" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"workingDays" INTEGER,
	"presentDays" INTEGER,
	"absenceDays" INTEGER,
	"paidLeaveTaken" INTEGER,
	"unpaidLeaveTaken" INTEGER,
	"lateCount" INTEGER NOT NULL DEFAULT 0,
	"overtimeHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"overtimeBonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"lateMarkPenalty" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"taxRegime" TEXT NOT NULL DEFAULT 'NEW',
	"annualTaxableIncome" DOUBLE PRECISION,
	"form16Generated" BOOLEAN NOT NULL DEFAULT false,
	"form16Data" JSONB,
	"payslipUrl" TEXT,
	"generatedAt" TIMESTAMP(3),
	"downloadedAt" TIMESTAMP(3),
	"emailSentAt" TIMESTAMP(3),
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP(3) NOT NULL,
	"deletedAt" TIMESTAMP(3),

	CONSTRAINT "Payslip_pkey" PRIMARY KEY ("id"),
	CONSTRAINT "Payslip_payrollEntryId_key" UNIQUE ("payrollEntryId")
);

ALTER TABLE "Payslip" ADD CONSTRAINT "Payslip_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payslip" ADD CONSTRAINT "Payslip_payrollEntryId_fkey" FOREIGN KEY ("payrollEntryId") REFERENCES "PayrollEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS "PayrollEarnings" (
	"id" SERIAL NOT NULL,
	"payrollEntryId" INTEGER NOT NULL,
	"basicSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"hra" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"specialAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"da" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"bonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"overtime" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"incentive" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"reimbursements" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"totalEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP(3) NOT NULL,
	"deletedAt" TIMESTAMP(3),

	CONSTRAINT "PayrollEarnings_pkey" PRIMARY KEY ("id"),
	CONSTRAINT "PayrollEarnings_payrollEntryId_key" UNIQUE ("payrollEntryId")
);

ALTER TABLE "PayrollEarnings" ADD CONSTRAINT "PayrollEarnings_payrollEntryId_fkey" FOREIGN KEY ("payrollEntryId") REFERENCES "PayrollEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS "PayrollDeduction" (
	"id" SERIAL NOT NULL,
	"payrollEntryId" INTEGER NOT NULL,
	"pfEmployeeContribution" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"pfEmployerContribution" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"esiContribution" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"professionalTax" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"tdsDeducted" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"lossOfPay" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"advanceRecovery" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"otherDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"totalDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP(3) NOT NULL,
	"deletedAt" TIMESTAMP(3),

	CONSTRAINT "PayrollDeduction_pkey" PRIMARY KEY ("id"),
	CONSTRAINT "PayrollDeduction_payrollEntryId_key" UNIQUE ("payrollEntryId")
);

ALTER TABLE "PayrollDeduction" ADD CONSTRAINT "PayrollDeduction_payrollEntryId_fkey" FOREIGN KEY ("payrollEntryId") REFERENCES "PayrollEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS "TaxDeclaration" (
	"id" SERIAL NOT NULL,
	"employeeId" INTEGER NOT NULL,
	"year" INTEGER NOT NULL,
	"investment80C" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"investment80D" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"investment80CCD" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"hraExemption" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"standardDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"otherIncome" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"otherIncomeTaxed" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"exerciseStock" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"estimatedTaxableIncome" DOUBLE PRECISION,
	"approvalStatus" TEXT NOT NULL DEFAULT 'PENDING',
	"approvedBy" INTEGER,
	"approvedAt" TIMESTAMP(3),
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP(3) NOT NULL,
	"deletedAt" TIMESTAMP(3),

	CONSTRAINT "TaxDeclaration_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "TaxDeclaration_employeeId_year_idx" ON "TaxDeclaration"("employeeId", "year");
ALTER TABLE "TaxDeclaration" ADD CONSTRAINT "TaxDeclaration_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS "Form16" (
	"id" SERIAL NOT NULL,
	"employeeId" INTEGER NOT NULL,
	"year" INTEGER NOT NULL,
	"panNumber" TEXT,
	"grossIncome" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"taxableIncome" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"totalTaxPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"grossSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"standardDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"interestIncomeUnderSection80A" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"investmentUnder80C" DOUBLE PRECISION NOT NULL DEFAULT 0,
	"tfcData" JSONB,
	"generatedAt" TIMESTAMP(3),
	"pdfUrl" TEXT,
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP(3) NOT NULL,
	"deletedAt" TIMESTAMP(3),

	CONSTRAINT "Form16_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Form16_employeeId_year_idx" ON "Form16"("employeeId", "year");
ALTER TABLE "Form16" ADD CONSTRAINT "Form16_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Attendance" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "LedgerEntry" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "CampaignLead" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Timesheet" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "LeaveRequest" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "TicketType" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "MarketingCampaign" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ProjectLink" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "DynamicForm" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ProductCategory" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "FileAttachment" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "SalaryStructure" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PayrollCycle" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PayrollEntry" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Payslip" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PayrollEarnings" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PayrollDeduction" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "TaxDeclaration" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Form16" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "JobOpening" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Candidate" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Interview" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "GoalCycle" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Goal" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "PerformanceReview" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
