DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'Activity',
    'ActivityTimeline',
    'ActivityTimelineComment',
    'Attendance',
    'AuditLog',
    'CampaignLead',
    'Candidate',
    'Contact',
    'Deal',
    'DynamicForm',
    'Event',
    'Expense',
    'File',
    'FileActivity',
    'FileAttachment',
    'Form16',
    'FormSubmission',
    'Goal',
    'GoalCycle',
    'ImportLog',
    'Interview',
    'Invoice',
    'JobOpening',
    'Lead',
    'LeaveRequest',
    'LedgerEntry',
    'MarketingCampaign',
    'Notification',
    'NotificationDeliveryLog',
    'NotificationPreference',
    'NotificationRecipient',
    'Payment',
    'PayrollConfig',
    'PayrollCycle',
    'PayrollDeduction',
    'PayrollEarnings',
    'PayrollEntry',
    'Payslip',
    'PerformanceReview',
    'Product',
    'ProductCategory',
    'Project',
    'ProjectLink',
    'ProjectMember',
    'ProjectMessage',
    'Quote',
    'QuoteItem',
    'SalaryStructure',
    'Shift',
    'Task',
    'TaxDeclaration',
    'Ticket',
    'Timesheet',
    'WorkflowAction',
    'WorkflowAssignment',
    'WorkflowComment',
    'WorkflowHistory',
    'WorkflowInstance',
    'WorkflowNotification',
    'WorkflowStep'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ALTER COLUMN "organizationId" SET DEFAULT 1', table_name);
  END LOOP;
END $$;